# Generated by Django 5.2.9 on 2026-01-18 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Not provided', max_length=200)),
                ('email', models.EmailField(default='notprovided@example.com', max_length=254)),
                ('phone', models.CharField(default='Not provided', max_length=20)),
                ('location', models.CharField(default='Not specified', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('current_position', models.CharField(default='Not specified', max_length=200)),
                ('years_experience', models.CharField(default='Not specified', max_length=50)),
                ('skills', models.TextField(default='Not specified', help_text='Comma-separated list of skills')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notice_period', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('15_DAYS', '15 days'), ('30_DAYS', '30 days'), ('60_DAYS', '60 days'), ('90_DAYS', '90 days'), ('CUSTOM', 'Custom')], default='30_DAYS', max_length=20)),
                ('custom_notice', models.CharField(blank=True, max_length=100, null=True)),
                ('available_start_date', models.DateField(blank=True, null=True)),
                ('education_level', models.CharField(choices=[('HIGH_SCHOOL', 'High School'), ('ASSOCIATE', 'Associate Degree'), ('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('VOCATIONAL', 'Vocational/Trade School'), ('OTHER', 'Other')], default='BACHELOR', max_length=20)),
                ('degree', models.CharField(default='Not specified', max_length=200)),
                ('university', models.CharField(default='Not specified', max_length=200)),
                ('graduation_year', models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('resume', models.FileField(upload_to='applications/resumes/%Y/%m/%d/')),
                ('cover_letter', models.TextField()),
                ('additional_docs', models.FileField(blank=True, null=True, upload_to='applications/additional/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Extended'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('status_notes', models.TextField(blank=True, null=True)),
                ('withdraw_reason', models.TextField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(default=0, help_text='1-5 rating from employer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('employer_notes', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Application Status History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('location', models.CharField(max_length=500)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Screening Response',
                'verbose_name_plural': 'Screening Responses',
            },
        ),
    ]
