# Generated by Django 5.2.9 on 2026-01-18 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High School Diploma'), ('VOCATIONAL', 'Vocational/TESDA'), ('ASSOCIATE', 'Associate Degree'), ('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('NONE', 'No formal education required')], max_length=20, null=True)),
                ('experience_years', models.IntegerField(blank=True, choices=[(0, 'No experience (Entry level)'), (1, '1-2 years'), (3, '3-5 years'), (6, '6-10 years'), (11, '10+ years')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
            },
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('CHECKBOX', 'Checkbox')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('qualifications', models.TextField(blank=True, verbose_name='Qualifications')),
                ('education_level', models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High School Diploma'), ('VOCATIONAL', 'Vocational/TESDA'), ('ASSOCIATE', 'Associate Degree'), ('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('NONE', 'No formal education required')], max_length=20, null=True, verbose_name='Minimum Education Required')),
                ('experience_years', models.IntegerField(choices=[(0, 'No experience (Entry level)'), (1, '1-2 years'), (3, '3-5 years'), (6, '6-10 years'), (11, '10+ years')], default=0, verbose_name='Years of Experience Required')),
                ('skills', models.TextField(blank=True, verbose_name='Skills')),
                ('benefits', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('application_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
