# Generated by Django 5.2.9 on 2026-01-18 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Alert', 'verbose_name_plural': 'Job Alerts'},
        ),
        migrations.AddField(
            model_name='jobalert',
            name='email',
            field=models.EmailField(default='user@example.com', help_text='Where to send job alerts', max_length=254, verbose_name='Notification Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobalert',
            name='frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20, verbose_name='Alert Frequency'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote')], max_length=20, null=True, verbose_name='Job Type'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords (e.g., python, django, react)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alert Name'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['job_seeker', 'is_active'], name='jobs_jobale_job_see_f66b54_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['is_active', 'frequency'], name='jobs_jobale_is_acti_56d5c5_idx'),
        ),
    ]
