# Generated by Django 5.2.9 on 2026-01-18 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobalert_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobalert',
            name='jobs_jobale_job_see_f66b54_idx',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='job_seeker',
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='email',
            field=models.EmailField(blank=True, help_text='Where to send job alerts', max_length=254, null=True, verbose_name='Notification Email'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['user', 'is_active'], name='jobs_jobale_user_id_82ec0d_idx'),
        ),
    ]
