# Generated by Django 5.2.9 on 2026-01-20 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobalert_jobs_jobale_job_see_f66b54_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobalert',
            name='jobs_jobale_is_acti_56d5c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobalert',
            name='jobs_jobale_user_id_82ec0d_idx',
        ),
        migrations.RenameField(
            model_name='jobalert',
            old_name='job_type',
            new_name='employment_type',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='user',
        ),
        migrations.AddField(
            model_name='jobalert',
            name='job_seeker',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'JOB_SEEKER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobalert',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='education_level',
            field=models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High School Diploma'), ('VOCATIONAL', 'Vocational/TESDA'), ('ASSOCIATE', 'Associate Degree'), ('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('NONE', 'No formal education required')], max_length=20, null=True, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='experience_years',
            field=models.IntegerField(blank=True, choices=[(0, 'No experience (Entry level)'), (1, '1-2 years'), (3, '3-5 years'), (6, '6-10 years'), (11, '10+ years')], null=True, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('INSTANT', 'Instant')], default='DAILY', max_length=10, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='is_remote',
            field=models.BooleanField(blank=True, null=True, verbose_name='Remote Work'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='keyword',
            field=models.CharField(blank=True, help_text='Job title, skills, or company', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='location',
            field=models.CharField(blank=True, help_text='City, state, or remote', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='name',
            field=models.CharField(default='My Job Alert', max_length=200, verbose_name='Alert Name'),
        ),
    ]
